    - name: update the packages for debian 8
      apt:
        upgrade: yes
        update_cache: yes

    - name: upgrade the OS
      apt:
        upgrade: dist

    - name: copy sources.list to host
      template:
        src: templates/sources.list.j2
        dest: /etc/apt/sources.list
        force: yes

    - name: update the packages for debian 9
      apt:
        upgrade: yes
        update_cache: yes

    - name: upgrade the OS
      apt:
        upgrade: dist

    - name: reboot the debian 9 machine
      reboot:
